apiVersion: v1
kind: Template
metadata:
  name: hccm-frontend-mfe
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: cost-management-mfe
    spec:
      envName: ${ENV_NAME}
      title: 'Cost Management microfrontend (MFE) with Module Federation'
      deploymentRepo: https://github.com/project-koku/koku-ui-mfe
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/cost-management-mfe
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - title: ROS
          expandable: true
          routes:
            - appId: 'cost-management-mfe'
              title: 'Optimizations badge'
              href: '/staging/cost-management/optimizations/badge'
            - appId: 'cost-management-mfe'
              title: 'Optimizations link'
              href: '/staging/cost-management/optimizations/link'
            - appId: 'cost-management-mfe'
              title: 'Optimizations summary'
              href: "/staging/cost-management/optimizations/summary"
            - appId: 'cost-management-mfe'
              title: 'Optimizations table'
              href: '/staging/cost-management/optimizations/table'
            - appId: 'cost-management-mfe'
              title: 'Optimizations details'
              href: '/staging/cost-management/optimizations/details'
            - appId: 'cost-management-mfe'
              title: 'Optimizations breakdown'
              href: '/staging/cost-management/optimizations/breakdown'
        - title: OCM
          expandable: true
          routes:
            - appId: 'cost-management-mfe'
              title: 'Overview card'
              href: "/staging/cost-management/ocm/overview"
      module:
        manifestLocation: "/apps/cost-management-mfe/fed-mods.json"
        modules:
          - id: "cost-management-mfe"
            module: "./RootApp"
            routes:
              - pathname: /staging/cost-management
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/hccm-frontend-mfe
